import { useState, useEffect } from 'react';
import { Radio, TrendingUp, TrendingDown, CheckCircle2, XCircle, Clock, ArrowRight, Zap, BarChart3 } from 'lucide-react';

interface Signal {
  id: number;
  strategy_id: string;
  pair: string;
  direction: 'long' | 'short';
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  timeframe: string;
  status: 'active' | 'hit_tp' | 'hit_sl' | 'expired';
  confidence: 'high' | 'medium';
  fired_at: string;
  resolved_at: string | null;
  result_pnl_pct: number | null;
}

export default function Signals() {
  const [activeSignals, setActiveSignals] = useState<Signal[]>([]);
  const [signalHistory, setSignalHistory] = useState<Signal[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    loadSignals();
    const interval = setInterval(loadSignals, 30000);
    return () => clearInterval(interval);
  }, []);

  const loadSignals = async () => {
    try {
      const [activeRes, historyRes] = await Promise.all([
        fetch('/api/signals?status=active'),
        fetch('/api/signals/history?limit=50'),
      ]);

      const activeData = await activeRes.json();
      const historyData = await historyRes.json();

      setActiveSignals(activeData.signals || []);
      setSignalHistory(historyData.signals || []);
    } catch (err) {
      console.error('Failed to load signals');
    } finally {
      setIsLoading(false);
    }
  };

  const formatPrice = (price: number, pair: string) => {
    if (pair === 'BTC/USDT') return `$${Math.round(price)}`;
    if (pair === 'ES') return price.toFixed(2);
    return `$${price.toFixed(2)}`;
  };

  const formatTime = (timestamp: string) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    if (diffMins < 1440) return `${Math.floor(diffMins / 60)}h ago`;
    return `${Math.floor(diffMins / 1440)}d ago`;
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'hit_tp': return <CheckCircle2 className="h-4 w-4 text-primary" />;
      case 'hit_sl': return <XCircle className="h-4 w-4 text-red-400" />;
      case 'expired': return <Clock className="h-4 w-4 text-muted-foreground" />;
      default: return <Radio className="h-4 w-4 text-primary animate-pulse" />;
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'hit_tp': return 'Hit TP';
      case 'hit_sl': return 'Hit SL';
      case 'expired': return 'Expired';
      default: return 'Active';
    }
  };

  const calculateStats = () => {
    const resolved = signalHistory.filter(s => s.status === 'hit_tp' || s.status === 'hit_sl');
    const wins = resolved.filter(s => s.status === 'hit_tp').length;
    const winRate = resolved.length > 0 ? (wins / resolved.length * 100).toFixed(1) : '0';
    const avgRR = resolved.length > 0
      ? (resolved.reduce((sum, s) => sum + (s.result_pnl_pct || 0), 0) / resolved.length).toFixed(2)
      : '0';

    return { winRate, avgRR, total: resolved.length };
  };

  const stats = calculateStats();

  return (
    <div className="min-h-screen pt-24 pb-16 px-4">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-6 text-xs font-bold tracking-widest uppercase"
               style={{ background: 'rgba(0,255,200,0.07)', border: '1px solid rgba(0,255,200,0.22)', color: '#00ffc8' }}>
            <Radio className="h-3.5 w-3.5" />
            <span>Live Signals</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight mb-4">
            Algo{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-secondary to-accent">
              Signals
            </span>
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto text-sm leading-relaxed">
            Real-time trading signals generated by our institutional-grade strategies. Follow along and learn systematic trading.
          </p>
        </div>

        {/* Stats Bar */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <div className="p-4 rounded-xl text-center" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
            <div className="text-2xl font-black text-primary mb-1">{stats.winRate}%</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-wider">Win Rate</div>
          </div>
          <div className="p-4 rounded-xl text-center" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
            <div className="text-2xl font-black text-secondary mb-1">{stats.avgRR}x</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-wider">Avg RR</div>
          </div>
          <div className="p-4 rounded-xl text-center" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
            <div className="text-2xl font-black text-accent mb-1">{stats.total}</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-wider">Total Signals</div>
          </div>
        </div>

        {/* Active Signals */}
        <div className="mb-12">
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <Radio className="h-5 w-5 text-primary" />
            Active Signals
          </h2>

          {isLoading ? (
            <div className="p-12 text-center rounded-2xl" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
              <div className="animate-spin h-8 w-8 border-2 border-primary border-t-transparent rounded-full mx-auto mb-4" />
              <p className="text-muted-foreground">Loading signals...</p>
            </div>
          ) : activeSignals.length === 0 ? (
            <div className="p-12 text-center rounded-2xl" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
              <Radio className="h-12 w-12 text-muted-foreground/30 mx-auto mb-4" />
              <p className="text-muted-foreground">No active signals right now. Check back soon!</p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {activeSignals.map((signal) => (
                <div
                  key={signal.id}
                  className="rounded-2xl p-5 transition-all hover:scale-[1.01]"
                  style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(0,255,200,0.15)', backdropFilter: 'blur(16px)' }}
                >
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-3">
                      <div
                        className={`w-10 h-10 rounded-lg flex items-center justify-center ${
                          signal.direction === 'long' ? 'bg-primary/10' : 'bg-red-400/10'
                        }`}
                      >
                        {signal.direction === 'long' ? (
                          <TrendingUp className="h-5 w-5 text-primary" />
                        ) : (
                          <TrendingDown className="h-5 w-5 text-red-400" />
                        )}
                      </div>
                      <div>
                        <div className="text-sm font-bold text-foreground">{signal.pair}</div>
                        <div className="text-[10px] text-muted-foreground uppercase tracking-wider">
                          {signal.strategy_id === 'momentum-breakout' ? 'Momentum Breakout' : 'RSI Mean Reversion'}
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span
                        className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider ${
                          signal.confidence === 'high' ? 'text-primary bg-primary/10' : 'text-secondary bg-secondary/10'
                        }`}
                      >
                        {signal.confidence}
                      </span>
                      <span className="text-[10px] text-muted-foreground">{formatTime(signal.fired_at)}</span>
                    </div>
                  </div>

                  <div className="grid grid-cols-3 gap-3 mb-4">
                    <div className="p-2 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}>
                      <div className="text-[9px] text-muted-foreground uppercase tracking-wider mb-0.5">Entry</div>
                      <div className="text-sm font-bold text-foreground">{formatPrice(signal.entry_price, signal.pair)}</div>
                    </div>
                    <div className="p-2 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}>
                      <div className="text-[9px] text-muted-foreground uppercase tracking-wider mb-0.5">Stop Loss</div>
                      <div className="text-sm font-bold text-red-400">{formatPrice(signal.stop_loss, signal.pair)}</div>
                    </div>
                    <div className="p-2 rounded-lg" style={{ background: 'rgba(255,255,255,0.03)' }}>
                      <div className="text-[9px] text-muted-foreground uppercase tracking-wider mb-0.5">Take Profit</div>
                      <div className="text-sm font-bold text-primary">{formatPrice(signal.take_profit, signal.pair)}</div>
                    </div>
                  </div>

                  <div className="flex items-center justify-between">
                    <div className="text-[10px] text-muted-foreground">
                      Timeframe: <span className="text-foreground font-semibold">{signal.timeframe.toUpperCase()}</span>
                    </div>
                    <div className="flex items-center gap-1 text-[10px] text-primary animate-pulse">
                      <Radio className="h-3 w-3" />
                      <span className="font-semibold">Live</span>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Signal History */}
        <div>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <BarChart3 className="h-5 w-5 text-secondary" />
            Signal History
          </h2>

          <div className="rounded-2xl overflow-hidden" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
            {signalHistory.length === 0 ? (
              <div className="p-12 text-center">
                <Clock className="h-12 w-12 text-muted-foreground/30 mx-auto mb-4" />
                <p className="text-muted-foreground">No signal history yet.</p>
              </div>
            ) : (
              <table className="w-full">
                <thead>
                  <tr className="text-left text-[10px] text-muted-foreground uppercase tracking-wider border-b border-white/5">
                    <th className="px-6 py-4">Asset</th>
                    <th className="px-6 py-4">Strategy</th>
                    <th className="px-6 py-4">Direction</th>
                    <th className="px-6 py-4">Entry</th>
                    <th className="px-6 py-4">Result</th>
                    <th className="px-6 py-4">P&L</th>
                    <th className="px-6 py-4">Time</th>
                  </tr>
                </thead>
                <tbody>
                  {signalHistory.map((signal) => (
                    <tr key={signal.id} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                      <td className="px-6 py-4">
                        <span className="text-sm font-semibold text-foreground">{signal.pair}</span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-xs text-muted-foreground">
                          {signal.strategy_id === 'momentum-breakout' ? 'Momentum' : 'RSI'}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                          signal.direction === 'long' ? 'text-primary bg-primary/10' : 'text-red-400 bg-red-400/10'
                        }`}>
                          {signal.direction === 'long' ? <TrendingUp className="h-3 w-3" /> : <TrendingDown className="h-3 w-3" />}
                          {signal.direction}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-sm text-foreground">{formatPrice(signal.entry_price, signal.pair)}</span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-1.5">
                          {getStatusIcon(signal.status)}
                          <span className="text-xs text-foreground">{getStatusText(signal.status)}</span>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={`text-sm font-bold ${
                          signal.result_pnl_pct && signal.result_pnl_pct > 0 ? 'text-primary' : 'text-red-400'
                        }`}>
                          {signal.result_pnl_pct ? (signal.result_pnl_pct > 0 ? '+' : '') + signal.result_pnl_pct.toFixed(2) + '%' : '-'}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-xs text-muted-foreground">{formatTime(signal.fired_at)}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>

        {/* CTA */}
        <div className="mt-8 text-center">
          <p className="text-sm text-muted-foreground mb-4">
            Want instant signal alerts? Join our Telegram channel.
          </p>
          <a
            href="https://t.me/edgerift"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-bold transition-all hover:opacity-90"
            style={{ background: '#00ffc8', color: '#000' }}
          >
            <Zap className="h-4 w-4" />
            Get Telegram Alerts
            <ArrowRight className="h-4 w-4" />
          </a>
        </div>
      </div>
    </div>
  );
}
