import { Shield, FileText, Lock, AlertTriangle, CheckCircle2, TrendingUp } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen pt-24 pb-16 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-6 text-xs font-bold tracking-widest uppercase"
               style={{ background: 'rgba(0,255,200,0.07)', border: '1px solid rgba(0,255,200,0.22)', color: '#00ffc8' }}>
            <Shield className="h-3.5 w-3.5" />
            <span>Legal</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black tracking-tight mb-4">
            Terms of{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-secondary">
              Service
            </span>
          </h1>
          <p className="text-muted-foreground max-w-xl mx-auto text-sm leading-relaxed">
            Last updated: May 2026
          </p>
        </div>

        {/* Content */}
        <div className="space-y-8">
          <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <CheckCircle2 className="h-5 w-5 text-primary" />
            1. Acceptance
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            By accessing EDGERIFT you agree to these terms. If you disagree, do not use the platform.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-accent" />
            2. Educational Purpose Only
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            EDGERIFT is an educational platform. All content — courses, algorithmic strategies, buy/sell signals, and trading simulations — is provided for learning purposes only. Nothing on this platform constitutes financial advice, investment advice, or a recommendation to buy or sell any financial instrument.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <FileText className="h-5 w-5 text-secondary" />
            3. Trading Simulator
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            The simulator uses virtual money only. No real money is involved at any stage. Passing a simulator challenge does not entitle you to real capital, funding, or any financial reward. Performance in a simulated environment does not guarantee or predict performance in live markets.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <TrendingUp className="h-5 w-5 text-primary" />
            4. Signals & Strategies
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Buy/sell signals are generated by automated algorithms for educational demonstration. Past signal performance does not guarantee future results. You are solely responsible for any trading decisions you make based on content from this platform.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <Lock className="h-5 w-5 text-muted-foreground" />
            5. User Accounts
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            You are responsible for maintaining the security of your account. You must be 18 or older to register. We reserve the right to suspend accounts that violate these terms.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <FileText className="h-5 w-5 text-secondary" />
            6. Intellectual Property
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            All course content, strategy logic, code, and design is the property of EDGERIFT. You may not reproduce, distribute, or resell any platform content without written permission.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-red-400" />
            7. Limitation of Liability
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            EDGERIFT and its operators shall not be liable for any financial losses, direct or indirect, arising from use of information on this platform.
          </p>
        </section>

        <section className="rounded-2xl p-8" style={{ background: 'rgba(7,17,31,0.7)', border: '1px solid rgba(255,255,255,0.06)' }}>
          <h2 className="text-xl font-bold text-foreground mb-4 flex items-center gap-2">
            <FileText className="h-5 w-5 text-secondary" />
            8. Changes
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            We reserve the right to modify these terms at any time. Continued use of the platform constitutes acceptance of updated terms.
          </p>
        </section>
        </div>
      </div>
    </div>
  );
}
